version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Balu@8088
      MYSQL_DATABASE: expensemanager
      MYSQL_USER: root
      MYSQL_PASSWORD: Balu@8088

  app:
    build: .
    container_name: expensemanager-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/expensemanager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Balu@8088
